// Mock data — used as fallback when the backend is not available.
// Schema intentionally mirrors the backend JSON data shapes so UI
// components render correctly regardless of which data source is active.

export const MOCK_SHIPMENTS = [
  {
    id: 'SHP-001',
    trackingNo: 'TRK-20260120-001',
    origin: 'Mumbai Port (JNPT)',
    destination: 'Pune ICD (Khadki)',
    currentLocation: 'Khopoli, Maharashtra',
    cargoType: 'Pharmaceuticals – Vaccines',
    cargoCategory: 'cold-chain',
    priority: 'critical',
    weight: 4.5,
    weightUnit: 'tonnes',
    carrier: 'CAR-001',
    currentRoute: 'RT-001',
    expectedDelivery: '2026-01-21T06:00:00+05:30',
    status: 'in-transit',
    riskLevel: 'medium',
    temperatureSensitive: true,
    requiredTemperatureRange: { min: 2, max: 8 },
    description: 'Vaccine shipment for Pune cold storage. In transit via RT-001.',
    scenarioTag: 'A_NORMAL',
    analytics: {
      shipmentPriorityScore: 85,
      delayRiskScore: 15,
      coldChainRisk: 20,
      disruptionExposure: 'low',
      overallRiskScore: 22,
      estimatedDelayHours: 0,
      actionRequired: false,
      actionType: null,
    },
  },
  {
    id: 'SHP-002',
    trackingNo: 'TRK-20260118-002',
    origin: 'Mumbai Port (JNPT)',
    destination: 'Delhi NCR ICD (Tughlakabad)',
    currentLocation: 'Mumbai Port (JNPT) – Strike Zone',
    cargoType: 'Consumer Electronics – Mobile Phones',
    cargoCategory: 'high-value',
    priority: 'critical',
    weight: 12,
    weightUnit: 'tonnes',
    carrier: 'CAR-001',
    currentRoute: 'RT-003',
    expectedDelivery: '2026-01-22T18:00:00+05:30',
    status: 'delayed',
    riskLevel: 'critical',
    temperatureSensitive: false,
    requiredTemperatureRange: null,
    description: 'Blocked at JNPT due to port strike (DIS-001). Critical delay. Emergency reroute + carrier swap recommended.',
    activeDisruption: 'DIS-001',
    alternativeRoutes: ['RT-002'],
    alternativeCarriers: ['CAR-002', 'CAR-005'],
    suggestedVehicle: 'TR-101',
    scenarioTag: 'D_CRITICAL',
    analytics: {
      shipmentPriorityScore: 95,
      delayRiskScore: 92,
      coldChainRisk: 45,
      disruptionExposure: 'critical',
      overallRiskScore: 95,
      estimatedDelayHours: 72,
      actionRequired: true,
      actionType: 'EMERGENCY_REROUTE_AND_CARRIER_SWAP',
    },
  },
  {
    id: 'SHP-003',
    trackingNo: 'TRK-20260119-003',
    origin: 'Chennai Port',
    destination: 'Bengaluru ICD (Whitefield)',
    currentLocation: 'Vellore, Tamil Nadu',
    cargoType: 'Automotive Parts – OEM',
    cargoCategory: 'industrial',
    priority: 'high',
    weight: 8.2,
    weightUnit: 'tonnes',
    carrier: 'CAR-003',
    currentRoute: 'RT-004',
    expectedDelivery: '2026-01-21T14:00:00+05:30',
    status: 'at-risk',
    riskLevel: 'high',
    temperatureSensitive: false,
    requiredTemperatureRange: null,
    description: 'Delayed due to Cyclone Gaja flooding on RT-004. Alternative via Salem (RT-005) recommended.',
    activeDisruption: 'DIS-002',
    alternativeRoutes: ['RT-005'],
    scenarioTag: 'C_HIGH_RISK',
    analytics: {
      shipmentPriorityScore: 70,
      delayRiskScore: 68,
      coldChainRisk: 0,
      disruptionExposure: 'high',
      overallRiskScore: 72,
      estimatedDelayHours: 14,
      actionRequired: true,
      actionType: 'REROUTE',
    },
  },
  {
    id: 'SHP-004',
    trackingNo: 'TRK-20260121-004',
    origin: 'Ahmedabad Distribution Centre',
    destination: 'Delhi NCR ICD (Tughlakabad)',
    currentLocation: 'Jaipur, Rajasthan',
    cargoType: 'Apparel – Fast Fashion',
    cargoCategory: 'general',
    priority: 'standard',
    weight: 9,
    weightUnit: 'tonnes',
    carrier: 'CAR-004',
    currentRoute: 'RT-010',
    expectedDelivery: '2026-01-23T10:00:00+05:30',
    status: 'in-transit',
    riskLevel: 'low',
    temperatureSensitive: false,
    requiredTemperatureRange: null,
    description: 'Fast fashion export. In transit via NH-48. Normal conditions.',
    scenarioTag: 'A_NORMAL',
    analytics: {
      shipmentPriorityScore: 20,
      delayRiskScore: 6,
      coldChainRisk: 0,
      disruptionExposure: 'none',
      overallRiskScore: 6,
      estimatedDelayHours: 0,
      actionRequired: false,
      actionType: null,
    },
  },
  {
    id: 'SHP-005',
    trackingNo: 'TRK-20260118-005',
    origin: 'Kolkata Port (KoPT)',
    destination: 'Delhi NCR ICD (Tughlakabad)',
    currentLocation: 'Patna, Bihar',
    cargoType: 'Agricultural Produce – Frozen Shrimp',
    cargoCategory: 'perishable',
    priority: 'high',
    weight: 6.5,
    weightUnit: 'tonnes',
    carrier: 'CAR-006',
    currentRoute: 'RT-008',
    expectedDelivery: '2026-01-21T22:00:00+05:30',
    status: 'at-risk',
    riskLevel: 'high',
    temperatureSensitive: false,
    requiredTemperatureRange: null,
    description: 'Frozen shrimp export for Delhi cold storage. Using RT-008 affected by Varanasi road closure. Rail alternative RT-009 recommended.',
    activeDisruption: 'DIS-004',
    alternativeRoutes: ['RT-009'],
    alternativeCarriers: ['CAR-006'],
    scenarioTag: 'C_HIGH_RISK',
    analytics: {
      shipmentPriorityScore: 65,
      delayRiskScore: 72,
      coldChainRisk: 30,
      disruptionExposure: 'medium',
      overallRiskScore: 70,
      estimatedDelayHours: 5,
      actionRequired: true,
      actionType: 'REROUTE',
    },
  },
];

export const MOCK_DISRUPTIONS = [
  {
    id: 'DIS-001',
    type: 'Port Strike',
    subType: 'Labour Action',
    location: 'Mumbai Port (JNPT)',
    severity: 'critical',
    status: 'active',
    startTime: '2026-01-18T00:00:00+05:30',
    endTime: '2026-01-25T23:59:00+05:30',
    durationHoursEstimate: 192,
    affectedRoutes: ['RT-001', 'RT-003'],
    affectedCarriers: ['CAR-001'],
    description: 'Indefinite strike by port workers at JNPT. All container operations suspended.',
    impactEstimate: '~2,000 TEUs/day backlogged',
    source: 'Port Authority Advisory PA-2026-0120',
    analytics: {
      disruptionSeverityScore: 95,
      operationalImpact: 'full-block',
      estimatedDelayHours: 168,
      affectedShipmentCount: 2,
      resolutionProbability: 'low',
      cascadeRisk: 'high',
      disruptionTypeCode: 'PORT_STRIKE',
    },
  },
  {
    id: 'DIS-002',
    type: 'Severe Weather',
    subType: 'Cyclonic Storm',
    location: 'Bay of Bengal / Tamil Nadu Coast',
    severity: 'high',
    status: 'active',
    startTime: '2026-01-18T14:00:00+05:30',
    endTime: '2026-01-22T23:59:00+05:30',
    durationHoursEstimate: 106,
    affectedRoutes: ['RT-004'],
    affectedCarriers: [],
    description: 'Cyclonic storm Gaja tracking toward Tamil Nadu–AP coast. NH-48 flooding risk.',
    impactEstimate: '12–18 hour delays on Chennai corridor',
    source: 'IMD Advisory CYC-2026-0118',
    analytics: {
      disruptionSeverityScore: 72,
      operationalImpact: 'partial-delay',
      estimatedDelayHours: 15,
      affectedShipmentCount: 2,
      resolutionProbability: 'high',
      cascadeRisk: 'medium',
      disruptionTypeCode: 'WEATHER_CYCLONE',
    },
  },
  {
    id: 'DIS-003',
    type: 'Severe Weather',
    subType: 'Road Flooding',
    location: 'Tamil Nadu Coast – NH-48',
    severity: 'medium',
    status: 'active',
    startTime: '2026-01-19T08:00:00+05:30',
    endTime: '2026-01-21T18:00:00+05:30',
    durationHoursEstimate: 58,
    affectedRoutes: ['RT-004'],
    affectedCarriers: ['CAR-007'],
    description: 'Heavy rainfall causing waterlogging on NH-48 near Tindivanam.',
    impactEstimate: 'Delays of 3–5 hours per truck',
    source: 'NHAI Regional Advisory TN-2026-0119',
    analytics: {
      disruptionSeverityScore: 50,
      operationalImpact: 'partial-delay',
      estimatedDelayHours: 4,
      affectedShipmentCount: 1,
      resolutionProbability: 'high',
      cascadeRisk: 'low',
      disruptionTypeCode: 'WEATHER_FLOODING',
    },
  },
  {
    id: 'DIS-004',
    type: 'Road Closure',
    subType: 'Infrastructure Works',
    location: 'NH-19 – Varanasi Bypass, Uttar Pradesh',
    severity: 'medium',
    status: 'active',
    startTime: '2026-01-15T00:00:00+05:30',
    endTime: '2026-02-15T23:59:00+05:30',
    durationHoursEstimate: 768,
    affectedRoutes: ['RT-008'],
    affectedCarriers: [],
    description: 'NHAI 4-lane expansion work on NH-19 near Varanasi bypass. Heavy vehicle delays.',
    impactEstimate: '4–6 hour delay on Kolkata–Delhi road corridor',
    source: 'NHAI Project Notice NHAI-NH19-VAR-2026',
    analytics: {
      disruptionSeverityScore: 48,
      operationalImpact: 'partial-delay',
      estimatedDelayHours: 5,
      affectedShipmentCount: 2,
      resolutionProbability: 'medium',
      cascadeRisk: 'low',
      disruptionTypeCode: 'ROAD_CLOSURE_CONSTRUCTION',
    },
  },
  {
    id: 'DIS-005',
    type: 'Geopolitical Disruption',
    subType: 'Maritime Security',
    location: 'Straits of Hormuz / Arabian Sea',
    severity: 'high',
    status: 'monitoring',
    startTime: '2026-01-10T00:00:00+05:30',
    endTime: null,
    durationHoursEstimate: null,
    affectedRoutes: [],
    affectedCarriers: [],
    description: 'Heightened maritime security advisories in the Arabian Sea. Insurance premiums increased ~15%.',
    impactEstimate: 'Insurance cost increase ~15%; potential re-routing adds 2 days',
    source: 'IMO MSCHOA Advisory 2026-008',
    analytics: {
      disruptionSeverityScore: 60,
      operationalImpact: 'monitoring-only',
      estimatedDelayHours: 48,
      affectedShipmentCount: 0,
      resolutionProbability: 'unknown',
      cascadeRisk: 'medium',
      disruptionTypeCode: 'GEOPOLITICAL_MARITIME',
    },
  },
];

export const MOCK_FLEET = [
  {
    id: 'TR-101',
    vehicleNo: 'MH-04-AB-1101',
    vehicleType: 'Reefer Truck',
    make: 'Tata Prima 4028.S',
    location: 'Nhava Sheva ICD, Raigad',
    capacity: 15,
    capacityUnit: 'tonnes',
    currentLoad: 4.5,
    status: 'active',
    available: false,
    carrier: 'CAR-001',
    utilization: 30,
    utilizationUnit: 'percent',
    driver: 'Rajesh Kumar',
    lastService: '2026-01-10',
    coldChainEquipped: true,
    temperatureRange: { min: -5, max: 15 },
    notes: 'Transporting SHP-001 vaccines. Low utilisation.',
    scenarioTag: 'E_COLD_CHAIN_BREACH',
    analytics: {
      fleetUtilizationPct: 30,
      availableCapacityTonnes: 10.5,
      redeploymentPriority: 'high',
      isRedeploymentCandidate: true,
      redeploymentReason: 'Low utilisation – can absorb emergency SHP-002 cold-chain cargo',
      coldChainScore: 95,
      proximityToAffectedShipment: 'near',
    },
  },
  {
    id: 'TR-102',
    vehicleNo: 'MH-12-CD-2202',
    vehicleType: 'Container Truck',
    make: 'Ashok Leyland 4220',
    location: 'Mumbai Port (JNPT)',
    capacity: 20,
    capacityUnit: 'tonnes',
    currentLoad: 12,
    status: 'active',
    available: false,
    carrier: 'CAR-001',
    utilization: 60,
    utilizationUnit: 'percent',
    driver: 'Pradeep Patil',
    lastService: '2026-01-05',
    coldChainEquipped: false,
    temperatureRange: null,
    notes: 'Loaded with SHP-002 electronics. Stuck at JNPT due to DIS-001.',
    scenarioTag: 'D_CRITICAL',
    analytics: {
      fleetUtilizationPct: 60,
      availableCapacityTonnes: 8,
      redeploymentPriority: 'none',
      isRedeploymentCandidate: false,
      redeploymentReason: null,
      coldChainScore: 0,
      proximityToAffectedShipment: 'at-location',
    },
  },
  {
    id: 'TR-103',
    vehicleNo: 'GJ-05-EF-3303',
    vehicleType: 'Reefer Truck',
    make: 'Eicher Pro 6049',
    location: 'Mundra Port – Cold Zone',
    capacity: 10,
    capacityUnit: 'tonnes',
    currentLoad: 6,
    status: 'active',
    available: false,
    carrier: 'CAR-005',
    utilization: 60,
    utilizationUnit: 'percent',
    driver: 'Anil Mehta',
    lastService: '2026-01-12',
    coldChainEquipped: true,
    temperatureRange: { min: -2, max: 8 },
    notes: 'Transporting SHP-003 seafood.',
    scenarioTag: 'A_NORMAL',
    analytics: {
      fleetUtilizationPct: 60,
      availableCapacityTonnes: 4,
      redeploymentPriority: 'none',
      isRedeploymentCandidate: false,
      redeploymentReason: null,
      coldChainScore: 90,
      proximityToAffectedShipment: 'distant',
    },
  },
  {
    id: 'TR-104',
    vehicleNo: 'RJ-14-QR-9909',
    vehicleType: 'Container Truck',
    make: 'BharatBenz 3128R',
    location: 'Jaipur, Rajasthan',
    capacity: 20,
    capacityUnit: 'tonnes',
    currentLoad: 0,
    status: 'idle',
    available: true,
    carrier: 'CAR-004',
    utilization: 0,
    utilizationUnit: 'percent',
    driver: 'Ramesh Gupta',
    lastService: '2026-01-18',
    coldChainEquipped: false,
    temperatureRange: null,
    notes: 'Idle at Jaipur depot. Available for redeployment.',
    scenarioTag: 'H_IDLE_REDEPLOYMENT',
    analytics: {
      fleetUtilizationPct: 0,
      availableCapacityTonnes: 20,
      redeploymentPriority: 'medium',
      isRedeploymentCandidate: true,
      redeploymentReason: 'Idle – no current assignment',
      coldChainScore: 0,
      proximityToAffectedShipment: 'distant',
    },
  },
  {
    id: 'TR-105',
    vehicleNo: 'DL-01-MN-7707',
    vehicleType: 'Trailer',
    make: 'Tata Prima 5530.S',
    location: 'Delhi NCR ICD (Tughlakabad)',
    capacity: 40,
    capacityUnit: 'tonnes',
    currentLoad: 14,
    status: 'active',
    available: true,
    carrier: 'CAR-006',
    utilization: 35,
    utilizationUnit: 'percent',
    driver: 'Suresh Yadav',
    lastService: '2026-01-14',
    coldChainEquipped: false,
    temperatureRange: null,
    notes: 'Low utilisation. 26 tonnes headspace available.',
    scenarioTag: 'B_MEDIUM_RISK',
    analytics: {
      fleetUtilizationPct: 35,
      availableCapacityTonnes: 26,
      redeploymentPriority: 'medium',
      isRedeploymentCandidate: true,
      redeploymentReason: 'Low utilisation – large headspace',
      coldChainScore: 0,
      proximityToAffectedShipment: 'distant',
    },
  },
];

export const MOCK_FLEET_UTIL = {
  totalVehicles: 5,
  active: 3,
  idle: 1,
  maintenance: 0,
  // Key used by frontend Dashboard — must match backend fleetService.utilisation()
  utilisationPct: 37.0,
};

export const MOCK_COLD_CHAIN = [
  {
    id: 'CC-001',
    shipmentId: 'SHP-001',
    sensorId: 'SNS-001-A',
    timestamp: '2026-01-20T06:00:00+05:30',
    temperature: 4.2,
    humidity: 72,
    location: 'Khopoli, Maharashtra',
    status: 'normal',
    notes: 'Vaccine shipment in transit. Temperature nominal.',
    analytics: {
      temperatureDeviationFromMidpoint: -0.8,
      deviationFromUpperLimit: -3.8,
      isExcursion: false,
      excursionDurationMinutes: 0,
      alertLevel: 0,
      triggerAlert: false,
    },
  },
  {
    id: 'CC-002',
    shipmentId: 'SHP-001',
    sensorId: 'SNS-001-B',
    timestamp: '2026-01-20T06:00:00+05:30',
    temperature: 4.5,
    humidity: 74,
    location: 'Khopoli, Maharashtra',
    status: 'normal',
    notes: 'Secondary sensor confirms. Both readings consistent.',
    analytics: {
      temperatureDeviationFromMidpoint: -0.5,
      deviationFromUpperLimit: -3.5,
      isExcursion: false,
      excursionDurationMinutes: 0,
      alertLevel: 0,
      triggerAlert: false,
    },
  },
  {
    id: 'CC-003',
    shipmentId: 'SHP-002',
    sensorId: 'SNS-002-A',
    timestamp: '2026-01-20T08:00:00+05:30',
    temperature: 11.4,
    humidity: 82,
    location: 'Mumbai Port (JNPT) – Strike Zone Hold',
    status: 'critical',
    notes: 'CRITICAL EXCURSION: Temperature reached 11.4°C. Vaccines require 2–8°C storage. Immediate action required.',
    analytics: {
      temperatureDeviationFromMidpoint: 6.4,
      deviationFromUpperLimit: 3.4,
      isExcursion: true,
      excursionDurationMinutes: 60,
      alertLevel: 3,
      triggerAlert: true,
    },
  },
  {
    id: 'CC-004',
    shipmentId: 'SHP-002',
    sensorId: 'SNS-002-B',
    timestamp: '2026-01-20T09:00:00+05:30',
    temperature: 11.1,
    humidity: 81,
    location: 'Mumbai Port (JNPT) – Strike Zone Hold',
    status: 'critical',
    notes: 'Secondary sensor confirms excursion. Both sensors agree. Critical condition.',
    analytics: {
      temperatureDeviationFromMidpoint: 6.1,
      deviationFromUpperLimit: 3.1,
      isExcursion: true,
      excursionDurationMinutes: 60,
      alertLevel: 3,
      triggerAlert: true,
    },
  },
  {
    id: 'CC-005',
    shipmentId: 'SHP-001',
    sensorId: 'SNS-001-A',
    timestamp: '2026-01-20T08:30:00+05:30',
    temperature: 6.8,
    humidity: 72,
    location: 'Lonavala, Maharashtra',
    status: 'warning',
    notes: 'Temporary spike due to door opening at checkpoint. Recovered within 20 minutes.',
    analytics: {
      temperatureDeviationFromMidpoint: 1.8,
      deviationFromUpperLimit: -1.2,
      isExcursion: false,
      excursionDurationMinutes: 20,
      alertLevel: 1,
      triggerAlert: true,
    },
  },
];

export const MOCK_RECOMMENDATIONS = [
  {
    id: 'REC-000',
    priority: 'Critical',
    title: '🔴 Active disruption: Port Strike — Mumbai Port (JNPT)',
    description: 'Indefinite strike by port workers at JNPT. All container operations suspended. Affected routes: RT-001, RT-003. Est. delay: 168h.',
    action: 'MONITOR',
    disruptionId: 'DIS-001',
  },
  {
    id: 'REC-001',
    priority: 'Critical',
    title: '🚨 Emergency reroute + carrier swap — SHP-002',
    description: 'Shipment SHP-002 (Consumer Electronics) blocked at JNPT. Risk score: 95/100. Est. delay: 72h. Reroute via RT-002 and swap to CAR-002 or CAR-005.',
    action: 'EMERGENCY_REROUTE_AND_CARRIER_SWAP',
    shipmentId: 'SHP-002',
    alternativeRoutes: ['RT-002'],
    alternativeCarriers: ['CAR-002', 'CAR-005'],
    suggestedVehicle: 'TR-101',
  },
  {
    id: 'REC-002',
    priority: 'High',
    title: '🔀 Reroute recommended — SHP-003',
    description: 'Automotive parts delayed by Cyclone Gaja on RT-004. Risk score: 72/100. Est. delay: 14h. Salem route (RT-005) recommended.',
    action: 'REROUTE',
    shipmentId: 'SHP-003',
    alternativeRoutes: ['RT-005'],
    alternativeCarriers: [],
    suggestedVehicle: null,
  },
  {
    id: 'REC-003',
    priority: 'High',
    title: '🔀 Reroute recommended — SHP-005',
    description: 'Frozen shrimp on RT-008 affected by Varanasi road closure. Risk score: 70/100. Est. delay: 5h. Rail alternative RT-009 recommended.',
    action: 'REROUTE',
    shipmentId: 'SHP-005',
    alternativeRoutes: ['RT-009'],
    alternativeCarriers: ['CAR-006'],
    suggestedVehicle: null,
  },
];
